<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="ShowUsers.aspx.cs" Inherits="_328419122.Admin.ShowUsers" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <h3>Users</h3>
    <asp:GridView id="gridview1" runat="server" OnRowCancelingEdit="gridview1_RowCancelingEdit" OnRowDeleting="gridview1_RowDeleting" OnRowEditing="gridview1_RowEditing" OnRowUpdating="gridview1_RowUpdating" AutoGenerateDeleteButton ="true">
        <Columns>
                <asp:CommandField  ShowEditButton ="true"/>
            </Columns>
    </asp:GridView>

    <h4>Add a new User</h4>
        

        <table id="pTable">
        <tr>
            <td>Username</td>
            <td>
                <asp:TextBox ID="uname" Text="" runat="server" Width="150px"></asp:TextBox>
            </td>
            
        </tr>
        <tr>
            <td>Password</td>
            <td> 
                <asp:TextBox ID="pass" Text="" runat="server" Width="150px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>First name</td>
            <td>
                <asp:TextBox ID="fname" Text="" runat="server" Width="150px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>Last name</td>
            <td>
                <asp:TextBox ID="lname" runat="server" Width="150px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>Email</td>
            <td>
                <asp:TextBox ID="mail" runat="server" Width="150px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>
                <asp:Button ID="AddUser" runat="server" Text="add" OnClick="AddUser_Click" />
            </td>
        </tr>
    </table>

</asp:Content>
