<%@ Page Title="" Language="C#" MasterPageFile="~/Users/UserMaster.Master" AutoEventWireup="true" CodeBehind="SalFinal.aspx.cs" Inherits="_328419122.Users.SalFinal" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div>
        <br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="true" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" OnRowDeleting="GridView1_RowDeleting">
            <Columns>
                <asp:CommandField  ShowEditButton ="true"/>
            </Columns>
        </asp:GridView>

       
        <asp:Button runat="server" class="btn1" text="add from catalog" OnClick="Unnamed2_Click"/>
    </div>
    


    <div id="pay">
        <table>
        <tr>
            <td>Number of products</td>
            <td>
                <asp:Label ID="NumOfProducts" Text="" runat="server" Width="250px"></asp:Label>
            </td>
            
        </tr>
        <tr>
            <td>Total price</td>
            <td>
                <asp:Label ID="TotalPrice" Text="" runat="server" Width="50px"></asp:Label>
                <asp:DropDownList ID="D1" runat="server" AutoPostBack="true" Height="16px" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" Width="58px">
                    <asp:ListItem>ILS</asp:ListItem>
                    <asp:ListItem>EUR</asp:ListItem>
                    <asp:ListItem>USD</asp:ListItem>
                </asp:DropDownList>
            </td>
            
        </tr>
        
        <tr>
            <td>Card Number</td>
            <td>
                <asp:TextBox ID="cnum" Text="" runat="server" Width="150px"></asp:TextBox>
            </td>
            
        </tr>
        <tr>
            <td>CVC</td>
            <td>
                <asp:TextBox ID="cvc" runat="server" Width="150px"></asp:TextBox>
            </td>
           
        </tr>
        <tr>
            <td>ID</td>
            <td>
                <asp:TextBox ID="userId" runat="server" Width="150px"></asp:TextBox>
            </td>
          
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>
                <asp:Button ID="send" runat="server" Text="Pay" OnClick="Unnamed_Click" />
           
        </tr>
    </table>

    </div>



       
    

</asp:Content>
